apiVersion: v1
kind: Service
metadata:
  name: webhook-service
  namespace: default
  labels:
    control-plane: coherence
    app: coherence-operator
    version: v3.1.5
spec:
  ports:
    - name: https-webhook
      port: 443
      targetPort: webhook-server
  selector:
    app: coherence-operator
    control-plane: coherence
    version: v3.1.5
