
apiVersion: v1
kind: Service
metadata:
  name: webhook-service
  namespace: default
  labels:
# +helm-gen:scaffold:labels
    control-plane: coherence
spec:
  ports:
    - port: 443
      targetPort: 9443
  selector:
    control-plane: coherence
