apiVersion: v1
kind: Service
metadata:
  namespace: default
  name: controller-manager-metrics-service
  labels:
# +helm-gen:scaffold:labels
    control-plane: coherence
spec:
  ports:
  - name: https
    port: 8443
    targetPort: https
  selector:
    control-plane: coherence
