apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: metrics-reader
  labels:
# +helm-gen:scaffold:labels
    control-plane: coherence
rules:
- nonResourceURLs: ["/metrics"]
  verbs: ["get"]
