# permissions for end users to view coherence.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: coherence-viewer-role
  labels:
    control-plane: coherence
rules:
- apiGroups:
  - coherence.oracle.com
  resources:
  - coherence
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - coherence.oracle.com
  resources:
  - coherence/status
  verbs:
  - get
