# -------------------------------------------------------------
# This is the service account used by the Coherence Operator.
# -------------------------------------------------------------
apiVersion: v1
kind: ServiceAccount
metadata:
  name: coherence-operator
  labels:
    control-plane: coherence
