apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
    operators.operatorframework.io/builder: operator-sdk-v1.0.0
    operators.operatorframework.io/project_layout: go.kubebuilder.io/v2
  name: coherence-operator.v3.1.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: Coherence is the Schema for the coherences API
      kind: Coherence
      name: coherences.coherence.oracle.com
      version: v1
  description: Oracle Coherence Operator
  displayName: Coherence
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: true
    type: OwnNamespace
  - supported: true
    type: SingleNamespace
  - supported: true
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - coherence
  links:
  - name: Coherence Operator
    url: https://oracle.github.io/coherence-operator/docs/3.1.0
  maturity: alpha
  provider:
    name: Oracle
    url: https://oracle.github.io/coherence-operator/docs/3.1.0
  version: 3.1.0
