---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: operator-test
  name: coherence-operator
  labels:
    app: coherence-operator
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: operator-test
  name: coherence-operator
  labels:
    app: coherence-operator
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - pods/exec
  - services
  - endpoints
  - persistentvolumeclaims
  - events
  - configmaps
  - secrets
  - namespaces
  verbs:
  - '*'
- apiGroups:
  - apps
  resources:
  - deployments
  - daemonsets
  - replicasets
  - statefulsets
  verbs:
  - '*'
- apiGroups:
  - monitoring.coreos.com
  resources:
  - servicemonitors
  verbs:
  - get
  - create
- apiGroups:
  - apps
  resourceNames:
  - coherence-operator
  resources:
  - deployments/finalizers
  verbs:
  - update
- apiGroups:
  - coherence.oracle.com
  resources:
  - '*'
  verbs:
  - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: operator-test
  name: coherence-operator
  labels:
    app: coherence-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: coherence-operator
subjects:
- kind: ServiceAccount
  name: coherence-operator
  namespace: operator-test
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: coherence-operator
  labels:
    app: coherence-operator
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get
  - list
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - '*'
- apiGroups:
  - coherence.oracle.com
  resources:
  - '*'
  verbs:
  - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: coherence-operator
  labels:
    app: coherence-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: operator-test-coherence-operator
subjects:
- kind: ServiceAccount
  name: coherence-operator
  namespace: operator-test
